language: go
dist: trusty

go:
  - tip
  - 1.6.2
  - 1.5.4
  - 1.4.3

before_install:
  - go get github.com/pkg/errors
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -race ./...
  - ./updatecov.sh

notifications:
  email: false